# Generated by Django 4.0 on 2022-09-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='profile_pics/default_profile_pic.jpg', upload_to='profile_pics'),
        ),
    ]
