# Generated by Django 4.0 on 2022-09-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_room_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_code',
            field=models.CharField(default='A42f-m+4', max_length=8),
            preserve_default=False,
        ),
    ]
