# Generated by Django 4.0 on 2022-09-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_room_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_admins',
            field=models.ManyToManyField(related_name='Admins', to='base.Profile', verbose_name='Rooms admins'),
        ),
        migrations.AlterField(
            model_name='room',
            name='profiles',
            field=models.ManyToManyField(related_name='Members', to='base.Profile'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=100, verbose_name='Room Name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_photo',
            field=models.ImageField(default='room_pics/default_room_pic.png', upload_to='room_pics', verbose_name='Room Photo'),
        ),
    ]
