# Generated by Django 4.0 on 2022-09-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_room_room_admins_alter_room_profiles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='users_friends', to='base.Profile'),
        ),
    ]
